# Generated by Django 4.0.4 on 2022-05-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='points',
        ),
    ]
