# Generated by Django 3.2.9 on 2022-08-27 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_password_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 18, 47, 20, 684037)),
        ),
    ]
