# Generated by Django 4.0.4 on 2022-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figures',
            name='test',
            field=models.CharField(max_length=250, verbose_name='النص'),
        ),
    ]
