# Generated by Django 4.0.4 on 2022-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_figures_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figures',
            old_name='test',
            new_name='text',
        ),
    ]
