# Generated by Django 4.0.4 on 2022-05-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('pages', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiguresChoosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finshed_1', models.BooleanField(default=False)),
                ('is_finshed_2', models.BooleanField(default=False)),
                ('is_finshed_3', models.BooleanField(default=False)),
                ('is_finshed_4', models.BooleanField(default=False)),
                ('is_finshed_5', models.BooleanField(default=False)),
                ('is_finshed_6', models.BooleanField(default=False)),
                ('is_finshed_7', models.BooleanField(default=False)),
                ('figures_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_1', to='pages.figures', verbose_name='الشخصية')),
                ('figures_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_2', to='pages.figures', verbose_name='الشخصية')),
                ('figures_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_3', to='pages.figures', verbose_name='الشخصية')),
                ('figures_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_4', to='pages.figures', verbose_name='الشخصية')),
                ('figures_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_5', to='pages.figures', verbose_name='الشخصية')),
                ('figures_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_6', to='pages.figures', verbose_name='الشخصية')),
                ('figures_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_7', to='pages.figures', verbose_name='الشخصية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='المستحدم')),
            ],
        ),
    ]
