# Generated by Django 4.0.4 on 2022-05-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_figureschoosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureschoosed',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
