# Generated by Django 4.0.4 on 2022-05-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_figureschoosed_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figureschoosed',
            name='points',
        ),
    ]
