# Generated by Django 3.2.9 on 2022-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_figureschoosed_figures_1_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pointsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.IntegerField(default=0, verbose_name='من')),
                ('_to', models.IntegerField(default=0, verbose_name='الى')),
                ('text', models.TextField(verbose_name='النص الذي سوف يعرض للمستخدم')),
            ],
        ),
    ]
