# Generated by Django 3.2.9 on 2022-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_figures_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figures',
            name='example',
        ),
        migrations.AddField(
            model_name='question',
            name='example',
            field=models.TextField(blank=True, null=True, verbose_name='مثال'),
        ),
    ]
