# Generated by Django 3.2.9 on 2022-08-27 20:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20220827_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='figures',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
