# Generated by Django 4.1.1 on 2022-10-01 14:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20220827_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiguresInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', tinymce.models.HTMLField()),
                ('figures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.figures', verbose_name='السمة')),
            ],
        ),
    ]
