# Generated by Django 4.1.1 on 2022-10-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_figuresinfo_figures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figures',
            old_name='_example',
            new_name='_example',
        ),
    ]
