# Generated by Django 4.1.1 on 2022-10-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_rename_example_figures__example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figures',
            old_name='_example',
            new_name='example',
        ),
        migrations.RenameField(
            model_name='figures',
            old_name='_identification',
            new_name='identification',
        ),
    ]
